/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.FA;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jsonOperations.Escrita;
import jsonOperations.Leitura;
import usuarios.Administrador;
import usuarios.Funcionario;
import views.ApenasNumeros;
import views.ApenasNumeros;

/**
 *
 * @author Walter
 */
public class AlterarInfoFA extends javax.swing.JInternalFrame {

    private String baseFuncionarios = "./src/baseDeDados/funcionarios.json";
    private String baseAdministradores = "./src/baseDeDados/administradores.json";

    private Funcionario[] listaFuncionarios;
    private Administrador[] listaAdministrador;

    private Administrador administradorLogado;

    public Administrador getAdministradorLogado() {
        return administradorLogado;
    }

    public void setAdministradorLogado(Administrador administradorLogado) {
        this.administradorLogado = administradorLogado;
    }

    private Administrador administradorSelecionado = null;
    private Funcionario funcionarioSelecionado;

    public String getBaseFuncionarios() {
        return baseFuncionarios;
    }

    public void setBaseFuncionarios(String baseFuncionarios) {
        this.baseFuncionarios = baseFuncionarios;
    }

    public String getBaseAdministradores() {
        return baseAdministradores;
    }

    public void setBaseAdministradores(String baseAdministradores) {
        this.baseAdministradores = baseAdministradores;
    }

    public Administrador getAdministradorSelecionado() {
        return administradorSelecionado;
    }

    public void setAdministradorSelecionado(Administrador administradorSelecionado) {
        this.administradorSelecionado = administradorSelecionado;
    }

    public Funcionario getFuncionarioSelecionado() {
        return funcionarioSelecionado;
    }

    public void setFuncionarioSelecionado(Funcionario funcionarioSelecionado) {
        this.funcionarioSelecionado = funcionarioSelecionado;
    }

    public void setShowDados() {
        
        // Mostar os dados alterados usando objeto do tipo funcionario
        if (administradorSelecionado != null) { 
            funcionarioSelecionado = (Funcionario) administradorSelecionado;
        }

        this.cxID.setText(funcionarioSelecionado.getId());
        this.cxSenha.setText(funcionarioSelecionado.getSenha());
        this.cxNome.setText(funcionarioSelecionado.getNome());
        this.cxEndereco.setText(funcionarioSelecionado.getEndereco());
        this.cxTelefone.setText(funcionarioSelecionado.getTelefone());
        this.cxContas.setText(funcionarioSelecionado.getsetIdConta().toString());
        this.cxDataA.setText(funcionarioSelecionado.getDataAdmissao());
        this.cxDataD.setText(funcionarioSelecionado.getDataDemissao());
        
        // Anulando o objeto para não ter interferencia no funcionamento
        if (administradorSelecionado != null) {
            funcionarioSelecionado = null;
        }
        
    }

    public void setAtualizarDados() {
        if (funcionarioSelecionado != null) {
            for (Funcionario f : listaFuncionarios) {
                if (f.getId().equals(funcionarioSelecionado.getId())) {
                    funcionarioSelecionado = f;
                    break;
                }
            }
        } else {
            for (Administrador a : listaAdministrador) {
                if (a.getId().equals(administradorSelecionado.getId())) {
                    administradorSelecionado = a;
                    break;
                }
            }
        }
        setShowDados();
    }

    /**
     * Creates new form AdicionarCliente
     */
    public AlterarInfoFA() {
        initComponents();
        this.cxContas.setDocument(new ApenasNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxSenha = new javax.swing.JTextField();
        cxEndereco = new javax.swing.JTextField();
        cxTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cxContas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cxID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cxDataD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cxDataA = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();

        setTitle("Informações do colaborador");
        setPreferredSize(new java.awt.Dimension(700, 495));

        jLabel1.setText("Nome");

        jLabel2.setText("Senha");

        jLabel3.setText("Endereço");

        jLabel4.setText("Telefone");

        cxNome.setEditable(false);
        cxNome.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxNome.setMinimumSize(new java.awt.Dimension(385, 22));
        cxNome.setPreferredSize(new java.awt.Dimension(385, 22));

        cxSenha.setEditable(false);
        cxSenha.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxSenha.setMinimumSize(new java.awt.Dimension(385, 22));
        cxSenha.setPreferredSize(new java.awt.Dimension(385, 22));

        cxEndereco.setEditable(false);
        cxEndereco.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxEndereco.setMinimumSize(new java.awt.Dimension(385, 22));
        cxEndereco.setPreferredSize(new java.awt.Dimension(385, 22));

        cxTelefone.setEditable(false);
        cxTelefone.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxTelefone.setMinimumSize(new java.awt.Dimension(385, 22));
        cxTelefone.setPreferredSize(new java.awt.Dimension(385, 22));
        cxTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTelefoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Contas Associadas");

        cxContas.setEditable(false);
        cxContas.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxContas.setMinimumSize(new java.awt.Dimension(385, 22));
        cxContas.setPreferredSize(new java.awt.Dimension(385, 22));
        cxContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxContasMouseClicked(evt);
            }
        });
        cxContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxContasActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        cxID.setEditable(false);
        cxID.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxID.setMinimumSize(new java.awt.Dimension(385, 22));
        cxID.setPreferredSize(new java.awt.Dimension(385, 22));

        jLabel8.setText("Data de demição");

        cxDataD.setEditable(false);
        cxDataD.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxDataD.setMinimumSize(new java.awt.Dimension(385, 22));
        cxDataD.setPreferredSize(new java.awt.Dimension(385, 22));
        cxDataD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxDataDMouseClicked(evt);
            }
        });

        jLabel9.setText("Data de admição");

        cxDataA.setEditable(false);
        cxDataA.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxDataA.setMinimumSize(new java.awt.Dimension(385, 22));
        cxDataA.setPreferredSize(new java.awt.Dimension(385, 22));
        cxDataA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxDataAMouseClicked(evt);
            }
        });

        btnAlterar.setText("Escolher e salvar alterações");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(cxDataA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxContas, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(cxTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(cxDataD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cxContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDataA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(41, 41, 41)
                .addComponent(btnAlterar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTelefoneActionPerformed

    private void cxContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxContasActionPerformed

    private void cxContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxContasMouseClicked

    }//GEN-LAST:event_cxContasMouseClicked

    private void cxDataDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxDataDMouseClicked

    }//GEN-LAST:event_cxDataDMouseClicked

    private void cxDataAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxDataAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataAMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (administradorSelecionado != null) {
            try {

                listaAdministrador = Leitura.lerAdministradores(baseAdministradores);
                listaAdministrador = administradorLogado.alterarAdmin(administradorSelecionado.getId(), listaAdministrador);
                Escrita.escreverAdmin(listaAdministrador, baseAdministradores);
                setAtualizarDados();

            } catch (ParseException ex) {
                Logger.getLogger(AlterarInfoFA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (funcionarioSelecionado != null) {
            try {

                listaFuncionarios = Leitura.lerFuncionarios(baseFuncionarios);
                listaFuncionarios = administradorLogado.alterarFuncionario(funcionarioSelecionado.getId(), listaFuncionarios);
                Escrita.escreverFuncionario(listaFuncionarios, baseFuncionarios);
                setAtualizarDados();

            } catch (ParseException ex) {
                Logger.getLogger(AlterarInfoFA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JTextField cxContas;
    private javax.swing.JTextField cxDataA;
    private javax.swing.JTextField cxDataD;
    private javax.swing.JTextField cxEndereco;
    private javax.swing.JTextField cxID;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSenha;
    private javax.swing.JTextField cxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
