/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.FA;

import agencia.Agencia;
import contas.Conta;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import jsonOperations.Leitura;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Walter
 */
public class InfoAgenciaFA extends javax.swing.JInternalFrame {
    
    private String baseAgencias = "./src/baseDeDados/listaAgencias.json";

    public String getBaseAgencias() {
        return baseAgencias;
    }

    public void setBaseAgencias(String baseAgencias) {
        this.baseAgencias = baseAgencias;
    }
    
    public void setShowDadosAgencia(){
        List<Agencia> listaAgencias = Leitura.lerAgencias(baseAgencias);
        StringBuilder sb = new StringBuilder();
        int linhas = 6;
        for (Agencia agencia : listaAgencias){
            sb.append(agencia.toString());
            linhas += linhas;
        }
        this.ShowDados.setRows(linhas);
        this.ShowDados.setText(sb.toString());
    }
    
    /**
     * Creates new form InfoAgenciaFA
     */
    public InfoAgenciaFA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ShowDados = new javax.swing.JTextArea();

        setTitle("Informações de agências");
        setMaximumSize(new java.awt.Dimension(700, 495));
        setMinimumSize(new java.awt.Dimension(700, 495));
        setPreferredSize(new java.awt.Dimension(700, 495));

        ShowDados.setColumns(20);
        ShowDados.setRows(5);
        jScrollPane1.setViewportView(ShowDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ShowDados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
