/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.administrador;

import javax.swing.JOptionPane;
import jsonOperations.Escrita;
import jsonOperations.Leitura;
import usuarios.Administrador;
import usuarios.Funcionario;
import views.ApenasNumeros;

/**
 * Adiciona novos funcionarios
 *
 * @author Walter
 */
public class AdicionarFuncionario extends javax.swing.JInternalFrame {

    private Administrador administradorLogado;
    private String baseFuncionarios = "./src/baseDeDados/funcionarios.json";

    public Administrador getAdministradorLogado() {
        return administradorLogado;
    }

    public void setAdministradorLogado(Administrador administradorLogado) {
        this.administradorLogado = administradorLogado;
    }

    public String getBaseFuncionarios() {
        return baseFuncionarios;
    }

    public void setBaseFuncionarios(String baseFuncionarios) {
        this.baseFuncionarios = baseFuncionarios;
    }

    /**
     * Limpa todas os campos de texto
     */
    private void limparCX() {
        this.cxID.setText("");
        this.cxSenha.setText("");
        this.cxNome.setText("");
        this.cxEndereco.setText("");
        this.cxTelefone.setText("");
        this.cxData.setText("");
        this.cxContas.setText("");
    }

    /**
     * Creates new form AdicionarCliente
     */
    public AdicionarFuncionario() {
        initComponents();
        this.cxContas.setDocument(new ApenasNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxSenha = new javax.swing.JTextField();
        cxEndereco = new javax.swing.JTextField();
        cxTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cxContas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cxID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();

        setTitle("Adicionar novo funcionario");
        setPreferredSize(new java.awt.Dimension(700, 495));

        jLabel1.setText("Nome");

        jLabel2.setText("Senha");

        jLabel3.setText("Endereço");

        jLabel4.setText("Telefone");

        cxNome.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxNome.setMinimumSize(new java.awt.Dimension(385, 22));
        cxNome.setPreferredSize(new java.awt.Dimension(385, 22));

        cxSenha.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxSenha.setMinimumSize(new java.awt.Dimension(385, 22));
        cxSenha.setPreferredSize(new java.awt.Dimension(385, 22));

        cxEndereco.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxEndereco.setMinimumSize(new java.awt.Dimension(385, 22));
        cxEndereco.setPreferredSize(new java.awt.Dimension(385, 22));

        cxTelefone.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxTelefone.setMinimumSize(new java.awt.Dimension(385, 22));
        cxTelefone.setPreferredSize(new java.awt.Dimension(385, 22));
        cxTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTelefoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Contas Associadas");

        cxContas.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxContas.setMinimumSize(new java.awt.Dimension(385, 22));
        cxContas.setPreferredSize(new java.awt.Dimension(385, 22));
        cxContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxContasMouseClicked(evt);
            }
        });
        cxContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxContasActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        cxID.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxID.setMinimumSize(new java.awt.Dimension(385, 22));
        cxID.setPreferredSize(new java.awt.Dimension(385, 22));

        btnAdd.setText("Adicionar novo funcionario");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de admição");

        cxData.setMaximumSize(new java.awt.Dimension(385, 2147483647));
        cxData.setMinimumSize(new java.awt.Dimension(385, 22));
        cxData.setPreferredSize(new java.awt.Dimension(385, 22));
        cxData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cxDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxContas, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(cxTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(cxData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cxContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnAdd)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTelefoneActionPerformed

    private void cxContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxContasActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String id = this.cxID.getText();
        String senha = this.cxSenha.getText();
        String nome = this.cxNome.getText();
        String dataAdimissao = this.cxData.getText();
        String endereco = this.cxEndereco.getText();
        String telefone = this.cxTelefone.getText();
        String[] sContas = this.cxContas.getText().split(",");
        Funcionario novoFuncionario = administradorLogado.adicionarFuncionario(
                dataAdimissao, null, id, senha, nome,
                endereco, telefone); // criando novo funcionario
        for (String c : sContas) {
            novoFuncionario.setIdConta((Integer.parseInt(c.replaceAll("[^0-9]", "")))); //recuperando as informacoes de contas associadas
        }
        Funcionario[] listaFuncionarios = Leitura.lerFuncionarios(baseFuncionarios); //lista original
        int tamLista = listaFuncionarios.length + 1; // definindo o tamanho da nova lista para adicionar um novo objeto
        Funcionario[] novaListaFuncionarios = new Funcionario[tamLista]; // instanciando a nova lista
        for (int i = 0; i < tamLista; i++) {

            if (i < tamLista - 1) { // preenchendo a nova lista com objetos ja existentes
                novaListaFuncionarios[i] = listaFuncionarios[i];
            } else { // adicionando o novo objeto
                novaListaFuncionarios[i] = novoFuncionario;
            }

        }
        Escrita.escreverFuncionario(novaListaFuncionarios, baseFuncionarios); // salvando as informacoes
        JOptionPane.showMessageDialog(null, "Funcionário adicionado com sucesso!");
        limparCX();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cxContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxContasMouseClicked
        JOptionPane.showMessageDialog(null, "Digite as contas associadas separando por vírgula caso o cliente tenha mais de 1."
                + "\n Ex.: 00000, 00000");
    }//GEN-LAST:event_cxContasMouseClicked

    private void cxDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cxDataMouseClicked
        JOptionPane.showMessageDialog(null, "Digite a data no formato dd/mm/aaaa.");
    }//GEN-LAST:event_cxDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField cxContas;
    private javax.swing.JTextField cxData;
    private javax.swing.JTextField cxEndereco;
    private javax.swing.JTextField cxID;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSenha;
    private javax.swing.JTextField cxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
