/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.administrador;

import contas.Conta;
import contas.ContaCorrente;
import contas.ContaPoupanca;
import contas.ContaSalario;
import java.util.List;
import javax.swing.JOptionPane;
import jsonOperations.Escrita;
import jsonOperations.Leitura;
import usuarios.Administrador;

/**
 * Altera as informacoes da conta
 * 
 * @author Walter
 */
public class AlterarConta extends javax.swing.JInternalFrame {

    private Conta contaSelecionada;
    private Administrador administradorLogado = null;
    private String baseContas;

    public Administrador getAdministradorLogado() {
        return administradorLogado;
    }

    public void setAdministradorLogado(Administrador administradorLogado) {
        this.administradorLogado = administradorLogado;
    }

    public Conta getContaSelecionada() {
        return contaSelecionada;
    }

    public void setContaSelecionada(Conta contaSelecionada) {
        this.contaSelecionada = contaSelecionada;
    }

    public String getBaseContas() {
        return baseContas;
    }

    public void setBaseContas(String baseContas) {
        this.baseContas = baseContas;
    }
    
    /**
     * Preenche os campos de texto com as informacoes da contaSelecionada
     */
    public void setShowDados(){
        this.cxTipoConta.setText(contaSelecionada.getTipoConta());
        this.cxAgencia.setText(Integer.toString(contaSelecionada.getAgencia()));
        this.cxID.setText(Integer.toString(contaSelecionada.getIdConta()));
        this.cxNumeroConta.setText(Integer.toString(contaSelecionada.getNumeroConta()));
        this.cxSaldo.setText(Double.toString(contaSelecionada.getSaldo()));
        if (contaSelecionada instanceof ContaSalario contaSalario) {
            this.cxCNPJ.setText(contaSalario.getCnpjEmpresa());
        }
        if (contaSelecionada instanceof ContaCorrente contaCorrente) {
            this.cxTaxa.setText(Double.toString(contaCorrente.getTaxaManutencao()));
        }
        if (contaSelecionada instanceof ContaPoupanca contaPoupanca) {
            this.cxLimiteSaque.setText(Double.toString(contaPoupanca.getLimiteSaque()));
        }
    }
    
    /**
     * Pesquisa um objeto na lista em que for igual ao objeto contaSelecionada e 
     * preeche os campos de texto da interface
     * 
     * @param listaContas 
     */
    private void setAtualizarInfo(List<Conta> listaContas){
        for (Conta conta : listaContas) {
            if (contaSelecionada.getIdConta() == conta.getIdConta()) {
                contaSelecionada = conta;
                break;
            }
        }
            setShowDados();
    }

    /**
     * Creates new form MeusDados
     */
    public AlterarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cxCNPJ = new javax.swing.JTextField();
        cxSaldo = new javax.swing.JTextField();
        cxID = new javax.swing.JTextField();
        cxLimiteSaque = new javax.swing.JTextField();
        cxTaxa = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cxNumeroConta = new javax.swing.JTextField();
        cxTipoConta = new javax.swing.JTextField();
        cxAgencia = new javax.swing.JTextField();

        setTitle("Adicionar Conta");
        setMaximumSize(new java.awt.Dimension(700, 495));
        setMinimumSize(new java.awt.Dimension(700, 495));
        setPreferredSize(new java.awt.Dimension(700, 495));

        jLabel1.setText("Tipo da conta");

        jLabel2.setText("ID da conta");

        jLabel3.setText("Número da agência");

        jLabel4.setText("Saldo inicial da conta");

        jLabel5.setText("CNPJ da empresa (conta salário)");

        jLabel6.setText("Taxa de manutenção (conta corrente)");

        jLabel7.setText("Limite de saque (conta poupança)");

        cxSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSaldoActionPerformed(evt);
            }
        });

        cxTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTaxaActionPerformed(evt);
            }
        });

        btnSalvar.setText("Escolher e salvar alteraçõs");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel8.setText("Número da conta");

        cxNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaActionPerformed(evt);
            }
        });

        cxAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAgenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cxTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxLimiteSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxNumeroConta, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxID, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxTipoConta, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cxCNPJ))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cxSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cxCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cxLimiteSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTaxaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTaxaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (administradorLogado != null) {
            List<Conta> listaContas;
            listaContas = Leitura.lerContas(baseContas);
            listaContas = administradorLogado.alterarConta(contaSelecionada.getIdConta(), listaContas); // alterando informacoes da conta
            Escrita.escreverContas(listaContas, baseContas); // slavando alteracoes
            setAtualizarInfo(listaContas); // mostrando as alteracoes na tela
            JOptionPane.showMessageDialog(null, "Informações alteradas com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum administrador logado");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cxSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSaldoActionPerformed

    private void cxNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaActionPerformed

    private void cxAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAgenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cxAgencia;
    private javax.swing.JTextField cxCNPJ;
    private javax.swing.JTextField cxID;
    private javax.swing.JTextField cxLimiteSaque;
    private javax.swing.JTextField cxNumeroConta;
    private javax.swing.JTextField cxSaldo;
    private javax.swing.JTextField cxTaxa;
    private javax.swing.JTextField cxTipoConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
