/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.cliente;

import contas.Conta;
import java.util.List;

/**
 * Exibe as informacoes de contas do cliente
 * 
 * @author Walter
 */
public class ContasCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContasCliente
     */
    public ContasCliente() {
        initComponents();
    }

    /**
     * Pesquisa e mostra o resultado das informacoes das contas do cliente
     * 
     * @param listaContas 
     */
    public void setContasCliente(List<Conta> listaContas) {
        if (listaContas != null) {
            for (Conta conta : listaContas) {
                if (conta != null) {
                    ShowContas.setText(conta.toString());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowContas = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(2, 78, 148));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Minhas Contas");
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        ShowContas.setColumns(20);
        ShowContas.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShowContas, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ShowContas, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ShowContas;
    // End of variables declaration//GEN-END:variables
}
