/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import contas.Conta;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import jsonOperations.Leitura;
import org.json.simple.parser.ParseException;
import usuarios.Cliente;
import views.cliente.ContasCliente;
import views.cliente.DadosCliente;
import views.cliente.ValidarConta;

/**
 * Interface do cliente
 * 
 * @author Walter
 */
public class ClienteUI extends javax.swing.JFrame {
    
    private Cliente clienteLogado;
    private List<Conta> contasCliente = new ArrayList<>();
    
    /**
     * Creates new form ContaCorrenteUI
     */
    public ClienteUI() {
        initComponents();
    }

    public Cliente getClienteLogado() {
        return clienteLogado;
    }

    public void setClienteLogado(Cliente clienteLogado) {
        this.clienteLogado = clienteLogado;
    }

    public List<Conta> getContasCliente() {
        return contasCliente;
    }

    /**
     * Este metodo presquisa e adiciona a <code> List &lt;Conta&gt;  contasCliente </code> 
     * as contas associadas ao cliente para as operacoes da interface.
     * 
     * @param contasAssociadas
     * @throws ParseException 
     */
    public void setContasCliente(List<Integer> contasAssociadas) throws ParseException {
        String baseContas = "./src/baseDeDados/listaContas.json";
        List<Conta> listaContas = Leitura.lerContas(baseContas);
        for (Integer idConta : contasAssociadas){
            for (Conta conta : listaContas){
                if (conta.getIdConta() == idConta){
                    contasCliente.add(conta);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContaPainel = new javax.swing.JPanel();
        PainelCliente = new javax.swing.JDesktopPane();
        BarraMenuConta = new javax.swing.JMenuBar();
        DadosCliente = new javax.swing.JMenu();
        ContasCliente = new javax.swing.JMenu();
        OperacoesConta = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Cliente - WWBank");

        ContaPainel.setBackground(new java.awt.Color(0, 20, 73));

        PainelCliente.setPreferredSize(new java.awt.Dimension(700, 400));

        javax.swing.GroupLayout PainelClienteLayout = new javax.swing.GroupLayout(PainelCliente);
        PainelCliente.setLayout(PainelClienteLayout);
        PainelClienteLayout.setHorizontalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PainelClienteLayout.setVerticalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContaPainelLayout = new javax.swing.GroupLayout(ContaPainel);
        ContaPainel.setLayout(ContaPainelLayout);
        ContaPainelLayout.setHorizontalGroup(
            ContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaPainelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PainelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ContaPainelLayout.setVerticalGroup(
            ContaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        BarraMenuConta.setBackground(new java.awt.Color(1, 38, 119));

        DadosCliente.setForeground(new java.awt.Color(255, 255, 255));
        DadosCliente.setText("Meus dados");
        DadosCliente.setContentAreaFilled(false);
        DadosCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DadosCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DadosClienteMouseClicked(evt);
            }
        });
        DadosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadosClienteActionPerformed(evt);
            }
        });
        BarraMenuConta.add(DadosCliente);

        ContasCliente.setForeground(new java.awt.Color(255, 255, 255));
        ContasCliente.setText("Minhas Contas");
        ContasCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ContasCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContasClienteMouseClicked(evt);
            }
        });
        ContasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContasClienteActionPerformed(evt);
            }
        });
        BarraMenuConta.add(ContasCliente);

        OperacoesConta.setForeground(new java.awt.Color(255, 255, 255));
        OperacoesConta.setText("Operações da conta");
        OperacoesConta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OperacoesConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OperacoesContaMouseClicked(evt);
            }
        });
        OperacoesConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacoesContaActionPerformed(evt);
            }
        });
        BarraMenuConta.add(OperacoesConta);

        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSair(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        BarraMenuConta.add(Sair);

        setJMenuBar(BarraMenuConta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickSair(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSair
        //this.ShowSaldo.setText("Clicou Sair");
        System.exit(0);
    }//GEN-LAST:event_clickSair

    private void DadosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadosClienteActionPerformed
        DadosCliente show = new DadosCliente();
        this.PainelCliente.removeAll();
        this.PainelCliente.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_DadosClienteActionPerformed

    private void OperacoesContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacoesContaActionPerformed
       
    }//GEN-LAST:event_OperacoesContaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void ContasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContasClienteActionPerformed
        
    }//GEN-LAST:event_ContasClienteActionPerformed

    private void ContasClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContasClienteMouseClicked
        try {
            ContasCliente show = new ContasCliente();
            this.PainelCliente.removeAll();
            this.PainelCliente.add(show);
            setContasCliente(clienteLogado.getsetIdConta());
            show.setContasCliente(contasCliente);
            show.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(ClienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ContasClienteMouseClicked

    private void DadosClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DadosClienteMouseClicked
        DadosCliente show = new DadosCliente();
        show.setDadosCliente(clienteLogado);
        this.PainelCliente.removeAll();
        this.PainelCliente.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_DadosClienteMouseClicked

    private void OperacoesContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperacoesContaMouseClicked
        ValidarConta show = new ValidarConta();
        this.PainelCliente.removeAll();
        show.setClienteUI(this);
        show.setClienteLogado(clienteLogado);
        show.setContasCliente(clienteLogado.getsetIdConta());
        show.setVisible(true);
    }//GEN-LAST:event_OperacoesContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuConta;
    private javax.swing.JPanel ContaPainel;
    private javax.swing.JMenu ContasCliente;
    private javax.swing.JMenu DadosCliente;
    private javax.swing.JMenu OperacoesConta;
    private javax.swing.JDesktopPane PainelCliente;
    private javax.swing.JMenu Sair;
    // End of variables declaration//GEN-END:variables
}
