/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import contas.Conta;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import jsonOperations.Leitura;
import org.json.simple.parser.ParseException;
import usuarios.Cliente;
import usuarios.Funcionario;
import views.cliente.ValidarConta;
import views.funcionario.AdicionarConta;
import views.funcionario.AlterarInfoCliente;
import views.funcionario.AlterarSenha;
import views.funcionario.ClientesCadastrados;
import views.funcionario.ContasCadastradas;
import views.funcionario.InfoCliente;
import views.funcionario.MeusDados;
import views.funcionario.RemoverConta;
import views.funcionario.ValidarCliente;

/**
 *
 * @author Walter
 */
public class FuncionarioUI extends javax.swing.JFrame {
//////////////////////////////

    private Funcionario funcionarioLogado = new Funcionario(null, null, "F1020", "123", "Ana S", "Rua B", "9999855");
    ///////////////////////////////
    private String baseFuncionarios = "./src/baseDeDados/funcionarios.json";
    private String baseContas = "./src/baseDeDados/listaContas.json";
    private String baseClientes = "./src/baseDeDados/clientes.json";

    Cliente clienteSelecionado = null;

    public Cliente getClienteSelecionado() {
        return clienteSelecionado;
    }

    public void setClienteSelecionado(Cliente clienteSelecionado) {
        this.clienteSelecionado = clienteSelecionado;
    }

    public String getBaseContas() {
        return baseContas;
    }

    public void setBaseContas(String baseContas) {
        this.baseContas = baseContas;
    }

    public String getBaseFuncionarios() {
        return baseFuncionarios;
    }

    public void setBaseFuncionarios(String baseFuncionarios) {
        this.baseFuncionarios = baseFuncionarios;
    }

    public Funcionario getFuncionarioLogado() {
        return funcionarioLogado;
    }

    public void setFuncionarioLogado(Funcionario funcionarioLogado) {
        this.funcionarioLogado = funcionarioLogado;
    }

    public void setLimparAreaDeTrabalho() {
        this.AreaDeTrabalho.removeAll();
    }

    public void setAlterarCliente(AlterarInfoCliente alterarInfoCliente) {
        this.AreaDeTrabalho.add(alterarInfoCliente);
    }

    public void setInfoCliente(InfoCliente infoCliente) {
        this.AreaDeTrabalho.add(infoCliente);
    }

    /**
     * Creates new form AdministradorUI
     */
    public FuncionarioUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AreaDeTrabalho = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MinhaConta = new javax.swing.JMenu();
        MeusDados = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AlterarSenha = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        contasCadastradas = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        acessarInfoCliente = new javax.swing.JMenuItem();
        Separator = new javax.swing.JPopupMenu.Separator();
        alterarInfoCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Funcionário - WWBanck");
        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(780, 620));
        setSize(new java.awt.Dimension(780, 620));

        jPanel1.setBackground(new java.awt.Color(0, 20, 73));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));

        AreaDeTrabalho.setMaximumSize(new java.awt.Dimension(700, 495));
        AreaDeTrabalho.setMinimumSize(new java.awt.Dimension(700, 495));

        javax.swing.GroupLayout AreaDeTrabalhoLayout = new javax.swing.GroupLayout(AreaDeTrabalho);
        AreaDeTrabalho.setLayout(AreaDeTrabalhoLayout);
        AreaDeTrabalhoLayout.setHorizontalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        AreaDeTrabalhoLayout.setVerticalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MinhaConta.setText("Minha Conta");
        MinhaConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinhaConta.setMaximumSize(new java.awt.Dimension(100, 22));
        MinhaConta.setMinimumSize(new java.awt.Dimension(100, 22));
        MinhaConta.setPreferredSize(new java.awt.Dimension(100, 22));
        MinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinhaContaActionPerformed(evt);
            }
        });

        MeusDados.setText("Meus dados");
        MeusDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeusDadosMouseClicked(evt);
            }
        });
        MeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeusDadosActionPerformed(evt);
            }
        });
        MinhaConta.add(MeusDados);
        MinhaConta.add(jSeparator2);

        AlterarSenha.setText("Alterar senha");
        AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarSenhaActionPerformed(evt);
            }
        });
        MinhaConta.add(AlterarSenha);
        MinhaConta.add(jSeparator4);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MinhaConta.add(Sair);

        jMenuBar1.add(MinhaConta);

        jMenu2.setText("Contas");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(100, 22));
        jMenu2.setMinimumSize(new java.awt.Dimension(100, 22));
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 22));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        contasCadastradas.setText("Contas cadastradas");
        contasCadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contasCadastradasActionPerformed(evt);
            }
        });
        jMenu2.add(contasCadastradas);
        jMenu2.add(jSeparator5);

        jMenuItem4.setText("Adicionar conta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuItem5.setText("Remover conta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator7);

        jMenuItem1.setText("Ir para minha conta bancária");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clientes");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setMaximumSize(new java.awt.Dimension(100, 22));
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 22));

        jMenuItem9.setText("Clientes cadastrados");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);
        jMenu3.add(jSeparator6);

        acessarInfoCliente.setText("Acessar informações do cliente");
        acessarInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarInfoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(acessarInfoCliente);
        jMenu3.add(Separator);

        alterarInfoCliente.setText("Alterar informações do cliente");
        alterarInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarInfoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(alterarInfoCliente);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeusDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeusDadosMouseClicked

    }//GEN-LAST:event_MeusDadosMouseClicked

    private void MeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeusDadosActionPerformed
        MeusDados show = new MeusDados();
        show.setShowMeusDados(funcionarioLogado.toString());
        this.AreaDeTrabalho.removeAll();
        this.AreaDeTrabalho.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_MeusDadosActionPerformed

    private void AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarSenhaActionPerformed
        AlterarSenha show = new AlterarSenha();
        show.setFuncionarioUI(this);
        show.setBaseFuncionarios(baseFuncionarios);
        show.setFuncionarioLogado(funcionarioLogado);
        this.AreaDeTrabalho.removeAll();
        this.AreaDeTrabalho.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_AlterarSenhaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void contasCadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contasCadastradasActionPerformed
        try {
            List<Conta> listaContas = Leitura.lerContas(baseContas);
            StringBuilder sb = new StringBuilder();
            int linhas = 7;
            for (Conta c : listaContas) {
                sb.append(c.infoConta());
                linhas += linhas;
            }

            ContasCadastradas show = new ContasCadastradas();
            show.setShowContas(sb.toString(), linhas);
            this.AreaDeTrabalho.removeAll();
            this.AreaDeTrabalho.add(show);
            show.setVisible(true);

        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contasCadastradasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AdicionarConta show = new AdicionarConta();
        show.setFuncionarioLogado(funcionarioLogado);
        show.setBaseContas(baseContas);
        this.AreaDeTrabalho.removeAll();
        this.AreaDeTrabalho.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        RemoverConta show = new RemoverConta();
        show.setFuncionarioLogado(funcionarioLogado);
        show.setBaseContas(baseContas);
        this.AreaDeTrabalho.removeAll();
        this.AreaDeTrabalho.add(show);
        show.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            List<Cliente> listaClientes = Leitura.lerClientes(baseClientes);
            StringBuilder sb = new StringBuilder();
            int linhas = 7;
            for (Cliente c : listaClientes) {
                sb.append(c.toString());
                linhas += linhas;
            }

            ClientesCadastrados show = new ClientesCadastrados();
            show.setShowContas(sb.toString(), linhas);
            this.AreaDeTrabalho.removeAll();
            this.AreaDeTrabalho.add(show);
            show.setVisible(true);

        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void acessarInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarInfoClienteActionPerformed
        ValidarCliente show = new ValidarCliente();
        show.setFuncionarioLogado(funcionarioLogado);
        show.setInfoCliente(new InfoCliente());
        show.setFuncionarioUI(this);
        this.AreaDeTrabalho.removeAll();
        show.setVisible(true);

    }//GEN-LAST:event_acessarInfoClienteActionPerformed

    private void alterarInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarInfoClienteActionPerformed
        ValidarCliente show = new ValidarCliente();
        show.setFuncionarioLogado(funcionarioLogado);
        show.setAlterarInfoCliente(new AlterarInfoCliente());
        show.setFuncionarioUI(this);
        this.AreaDeTrabalho.removeAll();
        show.setVisible(true);
    }//GEN-LAST:event_alterarInfoClienteActionPerformed

    private void MinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinhaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinhaContaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ValidarConta show = new ValidarConta();
        this.AreaDeTrabalho.removeAll();
        show.setFuncionarioUI(this);
        show.setClienteLogado(funcionarioLogado);
        show.setContasCliente(funcionarioLogado.getsetIdConta());
        show.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterarSenha;
    private javax.swing.JPanel AreaDeTrabalho;
    private javax.swing.JMenuItem MeusDados;
    private javax.swing.JMenu MinhaConta;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JPopupMenu.Separator Separator;
    private javax.swing.JMenuItem acessarInfoCliente;
    private javax.swing.JMenuItem alterarInfoCliente;
    private javax.swing.JMenuItem contasCadastradas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
